DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS technology;
DROP TABLE IF EXISTS difficulty;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE technology (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
);

CREATE TABLE difficulty (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
);

CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	body TEXT NULL,
	link TEXT NOT NULL,
	technology INTEGER NOT NULL,
	difficulty INTEGER NOT NULL,

	FOREIGN KEY (author_id) REFERENCES user (id),
	FOREIGN KEY (technology) REFERENCES technology (id),
	FOREIGN KEY (difficulty) REFERENCES technology (id)
);
