"""empty message

Revision ID: f6fc6e7add8b
Revises: 580f46f46b08
Create Date: 2018-05-25 20:34:58.591734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fc6e7add8b'
down_revision = '580f46f46b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_difficulty_name'), 'difficulty', ['name'], unique=True)
    op.create_table('technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_name'), 'technology', ['name'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=250), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('technology', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('link_accessible', sa.Boolean(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('project_author', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['difficulty'], ['difficulty.id'], ),
    sa.ForeignKeyConstraint(['technology'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_created'), 'post', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_created'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_technology_name'), table_name='technology')
    op.drop_table('technology')
    op.drop_index(op.f('ix_difficulty_name'), table_name='difficulty')
    op.drop_table('difficulty')
    # ### end Alembic commands ###
